### PR TITLE
Allow to toggle off updating of `openTypeHeadCreated` when other changes occur

### LINKED ISSUE #94: `openTypeHeadCreated` should not be updated during normalization
According to [OpenType spec](https://learn.microsoft.com/en-us/typography/opentype/spec/head), this header has two very similar fields: `created` and `modified`. Their semantic meaning is not explained, but I think it's logical to assume that `created` is supposed to store the original creation date of the font, whereas `modified` would store the timestamp of the latest update to the font.
In the [UFO format specification](https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#opentype-head-table-fields), there's are several notes under the OpenType head Table Fields table, of which the following are relevant: 
> 5. `created` can be calculated by subtracting the _12:00 midnight, January 1, 1904_ (as specified in the head table documentation) from the date stored at `openTypeHeadCreated`.
> 6. `modified` should be set by the authoring tool.

Currently `psfnormalize` overwrites the `openTypeHeadCreated` date whenever it fixes something. I don't think it should do this.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Fixes #94.

I've only tested my fix locally with `psfnormalize` though. May I expect that the preexisting tests will at least make sure that my code doesn't introduce any regressions in functionality?

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@jvgaultney, please have a look. I've placed this parameter in `outparams` along with all other, but I'm thinking about adding more parameters into the `ufometadata` group, so this setting could probably go there as well.
As for these extra parameters: I want to add a possibility to keep some lib and/or fontinfo entries that `psfnormalize` would remove. I initially started adding `preserveLib` and `preserveFontinfo` params, but now I'm thinking perhaps I should just make all the stuff here configurable, and move current values to core.py as defauls, what do you think? :
https://github.com/silnrsi/pysilfont/blob/e9a3693f23951a6216517547acab5b8002a7b089/src/silfont/ufo.py#L348-L380

**Comment by jvgaultney** [comment]
I looked at your pull request earlier and it generally looks great - thank you! Our team members who maintain the project need a chance to review and test it before merging it, and that may take a few days.

I would be hesitant to add a whole lot of additional normalization parameters to the ones we already have, as that would tend to encourage more and more custom UFO normalization 'flavours', which is the opposite of our intention. Where there is a clear practical reason - such as with `openTypeHeadCreated` - it's reasonable to have a switch to turn it off.

The "checkfix" checks and fixes you show above are already optional and not run by default. They reflect our particular preferences and understanding of best practice and may not be applicable for everyone. For example, none of our projects have uncommon widths, so we use checkfix to always set `openTypeOS2WidthClass` to 5. That's not really normalization in a strict sense, though we do it at the same time as general normalization. 

What it seems that you're wanting is a way to create a custom checkfix configuration (profile?) that can be stored within a project. If that's the case then our Font Tech team will need to discuss how might be the best way to suggest that be done. What I know we probably wouldn't want is 15+ more new general normalization parameters. We might also want to split the checks and fixes, or separate best practice (`openTypeHheaAscender` = `ascender`) from limits (`openTypeOS2WidthClass` = 5). Before you do any work on this could you briefly summarize what strategy you think is best? It would be good to have an idea of which checks/fixes you would most like to control and why. Then we can discuss it as a Font Tech team. We meet once every three weeks so this may take a while to process.

Thanks again!

**Comment by rimas-kudelis** [comment]
I personally don't see an issue with having different normalization profiles per project: you could say you're providing solid defaults, but projects may overwrite them when they deem necessary,

What I personally want to override right now is:
1. heh, you guessed it, `openTypeOS2WidthClass` (because there just happens to be a Condensed subfamily in my repo)
2. retaining `openTypeNameUniqueID` as-is (although I don't find it particularly important, could live with the autogenerated value just as well)
3. ability to keep (for the time being) some entries that `psfnormalize` wants to remove.
   1. for example, I simply don't know what effect `postscriptBlueFuzz`, `postscriptBlueScale`, and `postscriptBlueShift` in `fontinfo.plist` have, and since I also have `postscriptBlueValues`, `postscriptOtherBlues`, `postscriptStemSnapH`, and `postscriptStemSnapV` in fontinfo, I think they may be useful for whatever hinting completeness?
   2.  and in case of `com.fontlab.v2.tth` in `lib.plist`, I just want to keep existing Fontlab's hinting-related info for now next to `public.truetype.instructions`, until I (or someone else) figure out how and whether to do and version these hinting instructions (I personally find the assembler code in `public.truetype.instructions` absolutely unreadable).
   3. I could of course rename these fields, but I feel like that would be a somewhat ugly workaround, so I'd rather keep these original names

**Comment by jvgaultney** [comment]
Thanks - comments on individual issues here:

`openTypeOS2WidthClass` - I'll recommend we no longer set this in checkfix. It was set that way early in our transition to a UFO workflow to avoid mistakes, but we don't really need that now.

`openTypeNameUniqueID` - In some ways this is irrelevant, as I don't think it's really even used, but I'd like to keep autogenerating it as standard.

`postscriptBlueFuzz`, `postscriptBlueScale`, `postscriptBlueShift` - These are only relevant if you are producing CFF-flavoured OpenType fonts, and even then their usefulness is questionable. Adobe even recommends that BlueFuzz not be set. Glyphs has a [good article that explains these](https://glyphsapp.com/learn/hinting-postscript-autohinting). I'd prefer we keep removing these until someone has a real need for them. Unless you are creating OT/CFF and *really* need manual control over scale and shift these are just useless clutter.

`com.fontlab.v2.tth` - I'd be in favour of removing this from the libdel list. FontLab remains a poor tool for anything UFO related, as it really messes up things. We later created a `psffixfontlab` script that tries to undo some of the those problems. Since the script removes this key there's less need to remove it in normalization.

If we make those changes to `openTypeOS2WidthClass` and `com.fontlab.v2.tth` then there may be no reason to add special controls for them.

Again, our intent with checkfix is to promote best practice as we best understand it so you don't end up with a bunch of useless or misleading junk in your UFOs.

**Comment by jvgaultney** [comment]
I've now pushed the changes to handling of `openTypeOS2WidthClass` and `com.fontlab.v2.tth`

**Comment by rimas-kudelis** [comment]
> I've now pushed the changes to handling of `openTypeOS2WidthClass` and `com.fontlab.v2.tth`

Thank you!

Now I'll just have to wait for a new release, I guess? :)

**Comment by jvgaultney** [comment]
You should be able to just pull changes and use it

**Comment by rimas-kudelis** [comment]
@jvgaultney, thanks for all the info! I also wonder why the normalizer wants to remove the `openTypeGaspRangeRecords` entries instead of replacing them with whatever the recommendation is. Fontbakery complains about this.

**Comment by jvgaultney** [comment]
I've remove it from the list of deletions. However, unless you really know what you're doing, and need fine control over gasp you should not be using it. That range control is also completely ignored in many rendering situations so is rarely useful unless you're targeting a particular environment that you know applies gasp properly. Autohinting may add or override it anyway. BTW - just because FB complains about something doesn't mean you have to change it. gasp is not a required table.

**Pull request merged**
